export enum CriterioDistribucion {
  VENTAS_NETAS = 'VENTAS_NETAS',
  HORAS_TRABAJADAS = 'HORAS_TRABAJADAS',
  PARTES_IGUALES = 'PARTES_IGUALES',
  CANTIDAD_CUENTAS = 'CANTIDAD_CUENTAS',
  MANUAL = 'MANUAL',
}
